-- Seed initial content from the existing static site so the public site's appearance
-- and copy stay identical at first launch. One-time seed — not written to be re-run.

insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$home.hero$str$, $str$hero$str$, $str$home$str$, $str$Startseite – Hero$str$, $json${"headline":"Stark. Beweglich. Bereit.","subline":"Fitness, Gesundheit und Kampfkunst – persönlich begleitet im Sportpark Pollack.","ctaPrimaryLabel":"Probetraining starten","ctaSecondaryLabel":"Meinen Bereich finden","image":"/media/hero/hero2-desktop.webp","imageMobile":"/media/hero/hero2-mobile.webp"}$json$::jsonb, 0, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$home.imagefilm$str$, $str$imagefilm$str$, $str$home$str$, $str$Startseite – Imagefilm$str$, $json${"eyebrow":"Der Imagefilm","headline":"Spür den Puls.","durationLabel":"1:22 Min","video":"/media/video/imagefilm.mp4","teaserVideo":"/media/video/imagefilm-teaser.mp4","poster":"/media/video/imagefilm-poster.webp"}$json$::jsonb, 1, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$home.trust_stats$str$, $str$trust_stats$str$, $str$home$str$, $str$Startseite – Kennzahlen$str$, $json${"items":["1.200 m² · moderne Trainingsfläche","6 · Trainingszonen","40+ · Parkplätze direkt vor Ort","1987 · Erfahrung seit"]}$json$::jsonb, 2, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$home.owner$str$, $str$owner$str$, $str$home$str$, $str$Startseite – Jürgen Pollack$str$, $json${"name":"Jürgen Pollack","role":"Inhaber und Geschäftsführer","intro":"Seit 1987 auf der Matte und im Kraftraum zuhause: Jürgen Pollack hat den Sportpark Pollack aus Überzeugung aufgebaut – dass Training mehr sein soll als Wiederholungen zählen, nämlich ein Weg zu einem gesünderen, stärkeren und selbstbewussteren Leben.","story":"Seine Erfahrung reicht von klassischem Fitness- und Bodybuilding-Training bis zur Rehabilitation nach Verletzungen – ein Spektrum, das bis heute prägt, wie im Sportpark Pollack trainiert wird: leistungsorientiert, wo es sinnvoll ist, und immer mit Blick auf Gesundheit und Nachhaltigkeit.\n\nÜber die Jahre hat er sich kontinuierlich weitergebildet – vom C- und B-Trainer bis zum Vital Coach, Ernährungsberater und FIVE Basic Coach. Als ausgebildeter Selbstverteidigungslehrer, Gewaltschutztrainer und UVSV-Fachkraft (Unfallverhütung und Sicherheit) bringt er zusätzliches Fachwissen für den sicheren, verantwortungsvollen Trainingsbetrieb mit.\n\nIn der Kampfkunst trägt er den 2. DAN Karate und hat über 200 Lehrgänge besucht – mit Weiterbildungen unter anderem in Boxen, Kickboxen, Krav Maga, Bodenkampf und Kyusho, die in Karate-, Kinderkarate- und Selbstverteidigungstraining einfließen.","qualifications":["Inhaber und Geschäftsführer","Trainingserfahrung seit 1987","Erfahrung in Fitness, Bodybuilding und Reha","C-Trainer-Lizenz","B-Trainer-Lizenz","Vital Coach","Ernährungsberater","FIVE Basic Coach","Selbstverteidigungslehrer","Gewaltschutztrainer","UVSV-Fachkraft","Karate 2. DAN","Mehr als 200 absolvierte Lehrgänge","Weiterbildungen u. a. in Boxen, Kickboxen, Krav Maga, Bodenkampf und Kyusho"],"portrait":"/media/about/juergen-pollack-portrait.webp"}$json$::jsonb, 3, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$home.notice$str$, $str$notice$str$, $str$home$str$, $str$Startseite – Hinweisbanner$str$, $json${"text":"","active":false}$json$::jsonb, 4, false);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.fitness$str$, $str$program$str$, $str$training$str$, $str$Training – Fitness$str$, $json${"title":"Fitness","shortDescription":"Kraftaufbau, Kondition und Vitalität auf 1.200 m² Trainingsfläche.","description":"Fitnesstraining im Sportpark Pollack ist mehr als Wiederholungen zählen: Es geht um Kraftaufbau, Muskelaufbau, bessere Kondition, Gewichtsreduktion und spürbar mehr Vitalität im Alltag. Auf unserer Trainingsfläche findest du alles, was modernes, gesundheitsorientiertes Muskeltraining braucht – von hochwertigen Technogym-Geräten bis zum Plate-Loaded-Bereich für schweres Training.\n\nOb du gerade erst anfängst, wieder einsteigst oder als erfahrener Athlet trainierst – unsere Trainer:innen zeigen dir die passende Übungsauswahl und Technik, damit du sicher und effektiv an dein Ziel kommst. Das Training lässt sich individuell auf deine Ausgangslage und dein Ziel abstimmen.","features":["Freihantelbereich und hochwertige Technogym-Kraftgeräte","Plate-Loaded-Bereich für schweres Training","Cardiozonen für Kondition und Ausdauer","Individuelle Trainingsplanerstellung","Einweisung und Betreuung für Einsteiger:innen","Geeignet für Anfänger, Wiedereinsteiger und erfahrene Sportler"],"ctaLabel":null,"image":"/media/training/fitness-frau.webp","video":null}$json$::jsonb, 0, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.technogym$str$, $str$program$str$, $str$training$str$, $str$Training – Technogym$str$, $json${"title":"Technogym","shortDescription":"Premium-Geräte für präzises, gelenkschonendes Krafttraining.","description":"Unsere Technogym-Geräte gehören zur Premiumklasse im Studiobau: präzise Bewegungsführung, hochwertige Verarbeitung und eine Auswahl, die dich vom Einstieg bis zum ambitionierten Training begleitet.","features":["Geführte Bewegungsbahnen","Für Einsteiger und Fortgeschrittene","Teil der 1.200 m² Trainingsfläche"],"ctaLabel":null,"image":"/media/training/fitness-mann.webp","video":null}$json$::jsonb, 1, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.plate-loaded$str$, $str$program$str$, $str$training$str$, $str$Training – Plate-Loaded / Hardcore Area$str$, $json${"title":"Plate-Loaded / Hardcore Area","shortDescription":"Der Bereich für ambitioniertes, schweres Krafttraining.","description":"In unserer Hardcore Area trainierst du mit Plate-Loaded-Maschinen und freien Gewichten dort, wo es auf Substanz statt Schnickschnack ankommt. Mit der Erweiterung 2026 wächst dieser Bereich um zusätzliche Technogym Plate-Loaded Maschinen – mehr Fläche, mehr Ausstattung, mehr Raum für schweres Training.","features":["Plate-Loaded-Maschinen","Freihantelbereich für schweres Training","Erweiterung um neue Technogym Plate-Loaded Geräte"],"ctaLabel":null,"image":"/media/training/hardcore-area.webp","video":null}$json$::jsonb, 2, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.milon$str$, $str$program$str$, $str$gesundheit$str$, $str$Gesundheit – Milon$str$, $json${"title":"Milon-Zirkel","shortDescription":"Geführtes Zirkeltraining für Kraft und Ausdauer – gelenkschonend und zeitsparend.","description":"Der Milon-Zirkel ist ein geführtes Zirkeltraining, das sich automatisch auf dich einstellt und dich in kurzer Zeit durch ein vollständiges Ganzkörpertraining führt. Er verbindet Kraft- und Ausdauertraining in einer Einheit – gelenkschonend, zeitsparend und für unterschiedliche Alters- und Leistungsgruppen gleichermaßen geeignet.\n\nBesonders geeignet für den (Wieder-)Einstieg ins Training, für gesundheitsorientiertes Training und als Ergänzung zum klassischen Krafttraining. Unser Team betreut dich bei der Einweisung und begleitet deinen Fortschritt.","features":["Automatische Gerätevoreinstellung","Kraft- und Ausdauertraining in einer Einheit","Kurze, effiziente Trainingseinheiten","Gelenkschonend und einsteigerfreundlich","Für unterschiedliche Alters- und Leistungsgruppen","Persönliche Betreuung und Einweisung"],"ctaLabel":null,"image":null,"video":null}$json$::jsonb, 0, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.five$str$, $str$program$str$, $str$gesundheit$str$, $str$Gesundheit – FIVE$str$, $json${"title":"FIVE Rücken- und Gelenkzentrum","shortDescription":"Gezieltes Rücken- und Gelenkkonzept für mehr Beweglichkeit und ein starkes Muskel- und Fasziensystem.","description":"FIVE ist ein eigenständiges Trainingskonzept speziell für Rücken und Gelenke. Im Zentrum stehen geführte Rückwärtsbewegungen an speziell dafür entwickelten Geräten – kontrolliert, sicher und gezielt auf die Muskulatur und Faszien ausgerichtet, die deinen Rücken im Alltag stützen.\n\nMit der Erweiterung 2026 bekommt FIVE einen eigenen, rund 60 m² großen Gesundheitsbereich – bewusst separat vom Kraftraum, für konzentriertes, ruhiges Training.\n\nFIVE ersetzt keine medizinische Behandlung und wir versprechen keine Heilung. Wenn du unter anhaltenden Rückenbeschwerden leidest, sprich zusätzlich mit deiner Ärztin oder deinem Arzt. Für viele Menschen mit alltagsbedingten Verspannungen ist FIVE dagegen ein guter Weg, aktiv etwas für Rücken und Beweglichkeit zu tun.","features":["Geführte Rückwärtsbewegungen für Rücken und Gelenke","Kräftigt Muskel- und Fasziensystem","Verbessert Beweglichkeit im Alltag","Eigener, separater Gesundheitsbereich (ca. 60 m², ab Erweiterung 2026)","FIVE Basic Coach vor Ort"],"ctaLabel":null,"image":"/media/gesundheit/five-bambus-moos.webp","video":null}$json$::jsonb, 1, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.inbody$str$, $str$program$str$, $str$gesundheit$str$, $str$Gesundheit – Körperanalyse (InBody)$str$, $json${"title":"InBody 270 Körperanalyse","shortDescription":"Körperzusammensetzung statt Waage allein – Grundlage für Trainings- und Ernährungsberatung.","description":"Die InBody 270 Körperzusammensetzungsanalyse zeigt dir deutlich mehr als eine Waage: Körperfettanteil, Muskel-Fett-Analyse, Wasserhaushalt, Viszeralfett sowie Protein- und Mineralgehalt – dazu deinen Grundumsatz als Orientierung für ein realistisches Zielgewicht.\n\nBMI und Körpergewicht allein zeigen nicht, woraus dein Körper wirklich besteht. Die InBody-Analyse macht Fortschritt sichtbar, auch wenn sich die Zahl auf der Waage kaum bewegt – und ist die Grundlage für eine fundierte Trainings- und Ernährungsberatung bei uns im Sportpark.","features":["Körperfettanteil und Muskel-Fett-Analyse","Wasserhaushalt und Viszeralfett","Protein- und Mineralgehalt","Grundumsatz als Basis für dein Zielgewicht","Trainings- und Ernährungsberatung im Anschluss","Verlaufskontrolle über mehrere Termine"],"ctaLabel":null,"image":null,"video":null}$json$::jsonb, 2, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.karate$str$, $str$program$str$, $str$kampfkunst$str$, $str$Kampfkunst – Karate$str$, $json${"title":"Karate","shortDescription":"Traditionelle Kampfkunst für Kondition, Kraft, Schnelligkeit und Konzentration.","description":"Karate im Sportpark Pollack verbindet traditionelle Technik mit moderner Trainingsmethodik. Du trainierst Kondition, Kraft, Schnelligkeit, Beweglichkeit und Konzentration – in einer Trainingsatmosphäre, die auf Respekt und gegenseitiger Unterstützung aufbaut.\n\nAngeleitet wirst du von Jürgen Pollack, der seit 1987 in der Kampfkunst aktiv ist, den 2. DAN Karate trägt und über 200 Lehrgänge absolviert hat – mit Erfahrungen unter anderem in Boxen, Kickboxen, Krav Maga, Bodenkampf und Kyusho, die in das Training einfließen.","features":["Für Einsteiger:innen und Fortgeschrittene","Kondition, Kraft, Schnelligkeit, Beweglichkeit, Konzentration","Respektvolle, faire Trainingsatmosphäre","Angeleitet von Jürgen Pollack (Karate 2. DAN, über 200 Lehrgänge)","Trainingserfahrung u. a. in Boxen, Kickboxen, Krav Maga, Bodenkampf und Kyusho"],"ctaLabel":null,"image":"/media/kampfkunst/karate-portrait.webp","video":"/media/video/karate.mp4"}$json$::jsonb, 0, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.kinderkarate$str$, $str$program$str$, $str$kampfkunst$str$, $str$Kampfkunst – Kinderkarate$str$, $json${"title":"Kinderkarate","shortDescription":"Karate für Kinder – Selbstvertrauen, klare Grenzen und Respekt, altersgerecht vermittelt.","description":"Kinderkarate fördert weit mehr als Technik: Selbstvertrauen, Selbstbehauptung, das Erkennen und Setzen klarer Grenzen sowie Disziplin und Respekt im Umgang miteinander. In altersgerechten Gruppen lernen Kinder spielerisch, aber mit klarer Struktur.\n\nDabei geht es uns nicht darum, Kindern Angst zu machen, sondern ihnen Sicherheit zu geben – auch für ganz alltägliche Situationen wie den Schulweg oder den Pausenhof. Ein selbstbewusstes Auftreten ist oft schon die beste Vorbeugung.","features":["Altersgerechte Gruppen","Förderung von Selbstvertrauen und Selbstbehauptung","Klare Grenzen setzen und erkennen","Sicherheit für Schulweg und Pausenhof","Disziplin und Respekt, spielerisch vermittelt"],"ctaLabel":null,"image":"/media/kampfkunst/kinderkarate.webp","video":null}$json$::jsonb, 1, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.selbstverteidigung$str$, $str$program$str$, $str$kampfkunst$str$, $str$Kampfkunst – Selbstverteidigung$str$, $json${"title":"Selbstverteidigung","shortDescription":"Grundlagen- und Aufbaukurs – realistisch, alltagstauglich, angeleitet von einem Gewaltschutztrainer.","description":"Unsere Selbstverteidigungskurse sind in einen Grundlagenkurs und einen Aufbaukurs gegliedert. Im Mittelpunkt stehen Gefahrenerkennung, der bewusste Einsatz von Stimme und Körpersprache sowie Selbstbehauptung – denn die wichtigste Selbstverteidigung ist oft die Flucht aus einer gefährlichen Situation, nicht der Kampf.\n\nErgänzend trainierst du einfache, auch unter Stress abrufbare Techniken in realistischen Stressdrills. Angeleitet wird das Training von Jürgen Pollack, ausgebildeter Selbstverteidigungslehrer und Gewaltschutztrainer. Auf Wunsch ist das Training auch als Personaltraining buchbar.\n\nWir arbeiten bewusst ohne reißerische Aussagen oder unbelegte Kriminalstatistiken – Selbstverteidigung bei uns bedeutet Sicherheit und Handlungsfähigkeit, nicht Angstmache.","features":["Grundlagenkurs und Aufbaukurs","Gefahrenerkennung, Stimme und Körpersprache","Selbstbehauptung – Flucht als wichtigste Option","Einfache Techniken unter Stress (Stressdrills)","Angeleitet von einem ausgebildeten Gewaltschutztrainer","Auch als Personaltraining buchbar"],"ctaLabel":null,"image":null,"video":null}$json$::jsonb, 2, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.yoga$str$, $str$program$str$, $str$regeneration$str$, $str$Regeneration – Yoga$str$, $json${"title":"Yoga & Kinderyoga","shortDescription":"NINYASA Yoga mit Trainerin Nina – Atmung, Beweglichkeit und innere Ruhe.","description":"Unser Yoga-Angebot läuft unter NINYASA Yoga, angeleitet von unserer Yoga- und Kinderyogalehrerin Nina. Im Mittelpunkt stehen Atemübungen, Meditation und verschiedene Yogastile – als Ausgleich zum Krafttraining oder als eigenständiges Training für Körper und Kopf.\n\nDie Kurse sind sowohl für Einsteiger:innen als auch für Fortgeschrittene geeignet. Für Kinder bieten wir eigene, altersgerechte Kinderyoga-Einheiten an.","features":["NINYASA Yoga mit Trainerin Nina","Atemübungen und Meditation","Verschiedene Yogastile","Für Einsteiger:innen und Fortgeschrittene","Eigenes Kinderyoga-Angebot"],"ctaLabel":null,"image":null,"video":null}$json$::jsonb, 0, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$program.regeneration$str$, $str$program$str$, $str$regeneration$str$, $str$Regeneration – Massage & Entspannung$str$, $json${"title":"Massage & brainLight","shortDescription":"Individuell wählbare Entspannungsprogramme für Körper und Kopf.","description":"Nach dem Training oder als bewusste Auszeit: In unserem eigenen Massageraum sorgt das brainLight-Regenerationssystem mit individuell wählbaren Programmen aus Massage, Licht und Ton für gezielte Entspannung.\n\nWir formulieren hier bewusst zurückhaltend: brainLight ist ein Entspannungsangebot, keine medizinische Behandlung, und wir versprechen keine heilende Wirkung. Es geht darum, nach der Belastung loszulassen und bewusst abzuschalten.","features":["brainLight-Massagesessel mit individuell wählbaren Programmen","Kombination aus Massage, Licht und Ton","Eigener, ruhiger Massageraum","Entspannung nach dem Training"],"ctaLabel":null,"image":null,"video":null}$json$::jsonb, 1, true);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$site.faq$str$, $str$faq$str$, $str$kontakt$str$, $str$Häufige Fragen$str$, $json${"items":[]}$json$::jsonb, 0, false);
insert into public.website_sections (slug, section_key, page, title, content, sort_order, visible) values ($str$site.contact$str$, $str$contact$str$, $str$kontakt$str$, $str$Kontaktdaten$str$, $json${"street":"Hohe Straße 12","zip":"74579","city":"Fichtenau","phone":"07962 / 71 13 970","email":"info@sportpark-pollack.de","whatsapp":"0172 / 86 44 603","instagramUrl":"","facebookUrl":""}$json$::jsonb, 1, true);

insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$Monatsbeitrag$str$, $str$mitgliedschaft$str$, $str$Reguläre Mitgliedschaft mit Zugang zur gesamten Trainingsfläche.$str$, $str$Preis auf Anfrage$str$, $json$["Zugang zu allen Trainingszonen","Laufzeit und Konditionen auf Anfrage"]$json$::jsonb, true, 0);
insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$Schülerpreis$str$, $str$mitgliedschaft$str$, $str$Vergünstigte Mitgliedschaft für Schüler:innen.$str$, $str$Preis auf Anfrage$str$, $json$["Für Schüler:innen mit gültigem Nachweis"]$json$::jsonb, true, 1);
insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$Schnuppermonat$str$, $str$probetraining$str$, $str$Einen Monat unverbindlich reintesten.$str$, $str$Preis auf Anfrage$str$, $json$["Zeitlich begrenzter Einstieg ohne lange Bindung"]$json$::jsonb, true, 2);
insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$Winterpaket$str$, $str$aktion$str$, $str$Saisonales Trainingspaket.$str$, $str$Preis auf Anfrage$str$, $json$["Saisonal verfügbar"]$json$::jsonb, true, 3);
insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$Zehnerkarte$str$, $str$einmalig$str$, $str$Zehn Trainingseinheiten flexibel nutzbar.$str$, $str$Preis auf Anfrage$str$, $json$["Flexibel, ohne feste Mitgliedschaft"]$json$::jsonb, true, 4);
insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$InBody-Analyse$str$, $str$einmalig$str$, $str$Einzelne Körperanalyse mit der InBody 270.$str$, $str$Preis auf Anfrage$str$, $json$["Auch ohne Mitgliedschaft buchbar"]$json$::jsonb, true, 5);
insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$Selbstverteidigungskurse$str$, $str$einmalig$str$, $str$Kursreihe Selbstverteidigung.$str$, $str$Preis auf Anfrage$str$, $json$["Angeleitet von Jürgen Pollack"]$json$::jsonb, true, 6);
insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$Personaltraining$str$, $str$einmalig$str$, $str$1:1-Betreuung nach deinem Ziel.$str$, $str$Preis auf Anfrage$str$, $json$["Individuelle Terminplanung"]$json$::jsonb, true, 7);
insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$Sondertarife$str$, $str$mitgliedschaft$str$, $str$Weitere Sondertarife, z. B. für Paare, Familien oder Firmen.$str$, $str$Preis auf Anfrage$str$, $json$["Individuell auf Anfrage"]$json$::jsonb, true, 8);
insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$Getränkeflat$str$, $str$einmalig$str$, null, $str$Preis auf Anfrage$str$, $json$[]$json$::jsonb, true, 9);
insert into public.offers (title, category, description, price_note, features, published, sort_order) values ($str$Aufnahme- und Servicepauschale$str$, $str$einmalig$str$, null, $str$Preis auf Anfrage$str$, $json$[]$json$::jsonb, true, 10);

insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$mon$str$, $str$08:30$str$, $str$12:30$str$, false, 0);
insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$mon$str$, $str$14:30$str$, $str$22:00$str$, false, 1);
insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$tue$str$, $str$08:30$str$, $str$12:30$str$, false, 0);
insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$tue$str$, $str$14:30$str$, $str$21:00$str$, false, 1);
insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$wed$str$, $str$14:30$str$, $str$22:00$str$, false, 0);
insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$thu$str$, $str$08:30$str$, $str$12:30$str$, false, 0);
insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$thu$str$, $str$14:30$str$, $str$22:00$str$, false, 1);
insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$fri$str$, $str$08:30$str$, $str$12:30$str$, false, 0);
insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$fri$str$, $str$14:30$str$, $str$21:00$str$, false, 1);
insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$sat$str$, $str$08:30$str$, $str$14:00$str$, false, 0);
insert into public.opening_hours (weekday, open_time, close_time, closed, sort_order) values ($str$sun$str$, $str$10:00$str$, $str$13:00$str$, false, 0);

insert into public.partners (name, description, link_url, visible, sort_order) values ($str$Hansefit$str$, $str$Hansefit ist ein wichtiger Partner des Sportpark Pollack. Als Hansefit-Mitglied kannst du bei uns trainieren – die genauen Konditionen und Zugangsregeln bestätigen wir dir gerne persönlich, da sie sich am jeweils aktuellen Hansefit-Tarif orientieren.$str$, null, true, 0);

insert into public.products (name, category, description, available_in_store, visible, sort_order) values ($str$MORE Nutrition$str$, $str$Supplements$str$, $str$Proteinpulver, Riegel und weitere Supplements von MORE Nutrition – bei uns direkt vor Ort erhältlich.$str$, true, true, 0);
insert into public.products (name, category, description, available_in_store, visible, sort_order) values ($str$ESN$str$, $str$Supplements$str$, $str$Ergänzendes Sortiment von ESN für dein Training und deine Ernährung – ebenfalls direkt im Sportpark.$str$, true, true, 1);

insert into public.team_members (name, role_title, bio, qualifications, focus_areas, is_owner, visible, sort_order) values ($str$Jürgen Pollack$str$, $str$Inhaber und Geschäftsführer$str$, $str$Seit 1987 auf der Matte und im Kraftraum zuhause: Jürgen Pollack hat den Sportpark Pollack aus Überzeugung aufgebaut – dass Training mehr sein soll als Wiederholungen zählen, nämlich ein Weg zu einem gesünderen, stärkeren und selbstbewussteren Leben.

Seine Erfahrung reicht von klassischem Fitness- und Bodybuilding-Training bis zur Rehabilitation nach Verletzungen – ein Spektrum, das bis heute prägt, wie im Sportpark Pollack trainiert wird: leistungsorientiert, wo es sinnvoll ist, und immer mit Blick auf Gesundheit und Nachhaltigkeit.

Über die Jahre hat er sich kontinuierlich weitergebildet – vom C- und B-Trainer bis zum Vital Coach, Ernährungsberater und FIVE Basic Coach. Als ausgebildeter Selbstverteidigungslehrer, Gewaltschutztrainer und UVSV-Fachkraft (Unfallverhütung und Sicherheit) bringt er zusätzliches Fachwissen für den sicheren, verantwortungsvollen Trainingsbetrieb mit.

In der Kampfkunst trägt er den 2. DAN Karate und hat über 200 Lehrgänge besucht – mit Weiterbildungen unter anderem in Boxen, Kickboxen, Krav Maga, Bodenkampf und Kyusho, die in Karate-, Kinderkarate- und Selbstverteidigungstraining einfließen.$str$, $json$["Trainingserfahrung seit 1987","Erfahrung in Fitness, Bodybuilding und Reha","C-Trainer-Lizenz","B-Trainer-Lizenz","Vital Coach","Ernährungsberater","FIVE Basic Coach","Selbstverteidigungslehrer","Gewaltschutztrainer","UVSV-Fachkraft","Karate 2. DAN","Mehr als 200 absolvierte Lehrgänge","Weiterbildungen u. a. in Boxen, Kickboxen, Krav Maga, Bodenkampf und Kyusho"]$json$::jsonb, $json$["Fitness & Bodybuilding","Rehabilitation","Karate","Kinderkarate","Selbstverteidigung"]$json$::jsonb, true, true, 0);
insert into public.team_members (name, role_title, bio, qualifications, focus_areas, is_owner, visible, sort_order) values ($str$Nina$str$, $str$Yoga- und Kinderyogalehrerin (NINYASA Yoga)$str$, $str$Unter dem Namen NINYASA Yoga leitet Nina das Yoga- und Kinderyoga-Angebot im Sportpark Pollack – mit Atemübungen, Meditation und verschiedenen Yogastilen für Einsteiger:innen ebenso wie für Fortgeschrittene.$str$, '[]'::jsonb, $json$["Yoga","Kinderyoga"]$json$::jsonb, false, true, 1);

